#!/bin/bash

# Install theme
echo -e "Installing theme"
sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/chimken/chimken.plymouth 100 &> /dev/null
echo -e "Selecting theme"
sudo update-alternatives --set default.plymouth /usr/share/plymouth/themes/chimken/chimken.plymouth &> /dev/null
echo -e "Updating initramfs"
sudo update-initramfs -u &> /dev/null
echo -e "Installation complete"
exit 0
